name: Generate Podcase Feeds
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */1 * * *"
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: nkowsik/potcast-generator@main
